import React from 'react';
import { ArrowRight, Bot, Check, Hash, MessageCircle, Search, Sparkles } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

function Nav({ navigate }) {
  return <header className="fixed left-1/2 top-6 z-20 flex w-[calc(100%-32px)] max-w-[970px] -translate-x-1/2 items-center justify-between rounded-full border border-white/60 bg-[#aabdd4]/75 px-6 py-3.5 text-sm text-white shadow-[0_16px_30px_rgba(44,68,94,0.18)] backdrop-blur-md md:px-8"><button onClick={() => navigate('/')} className="flex items-center gap-2 font-semibold"><span className="text-lg">↗</span> FlowInbox</button><nav className="hidden gap-8 md:flex"><a href="#agents">For Agents</a><a href="#mcp">MCP</a><a href="#teams">For Teams</a></nav><div className="flex items-center gap-2"><button onClick={() => navigate('/signin')} className="px-3 py-2">Login</button><button onClick={() => navigate('/signin')} className="rounded-full bg-[#f29a00] px-5 py-2 font-semibold">Get started</button></div></header>;
}

function MailMockup({ comments = false }) {
  return <div className="relative mx-auto w-full max-w-4xl overflow-hidden rounded-[24px] border border-white/75 bg-[#eef1fb]/90 p-2 shadow-[0_20px_50px_rgba(35,49,73,0.18)]"><div className="mb-2 flex gap-1.5 px-3 pt-1"><span className="h-2.5 w-2.5 rounded-full bg-[#ef9d94]" /><span className="h-2.5 w-2.5 rounded-full bg-[#eacb7d]" /><span className="h-2.5 w-2.5 rounded-full bg-[#9fc7ac]" /></div><div className="grid min-h-[260px] grid-cols-[1fr_0.76fr] gap-2"><div className="rounded-2xl bg-white p-4 text-left"><div className="flex items-center justify-between border-b border-[#edf0f4] pb-3 text-xs font-semibold"><span>{comments ? 'Project update and next steps' : 'Your receipt from Anthropic'}</span><span className="text-[#8192a2]">•••</span></div><div className="mt-5 flex gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#f08055] text-white">✦</span><div><p className="text-xs font-semibold">{comments ? 'Louis Lecat' : 'Anthropic'} <span className="font-normal text-[#9aa7b4]">· 1:30 PM</span></p><div className="mt-3 h-28 rounded-xl bg-[#f1f2ed] p-4 text-left"><p className="text-[10px] text-[#82909c]">Receipt from Anthropic, PBC</p><p className="mt-1 text-2xl font-semibold">€90.00</p><p className="mt-1 text-[10px] text-[#82909c]">Paid April 21, 2026</p></div></div></div></div><div className="rounded-2xl bg-[#eef0fb] p-4 text-left"><h3 className="text-sm font-semibold">{comments ? 'Comments' : 'Comments'}</h3><div className="mt-5 flex gap-2"><span className="h-7 w-7 rounded-full bg-[#e5a26e]" /><div className="text-xs"><p className="font-semibold">FlowInbox Agent <span className="font-normal text-[#8996a3]">· 1:30 PM</span></p><p className="mt-2 leading-5 text-[#5b6875]"><span className="text-[#3da276]">✓ Receipt matched</span><br />• Amount: $90<br />• Status: Already Present<br />• Confidence: 85%</p></div></div></div></div></div>;
}

export default function ForAgentsPage() {
  const navigate = useNavigate();
  return <div className="min-h-screen overflow-hidden bg-[#fbfbfd] text-[#202631]"><Nav navigate={navigate} /><main>
    <section id="agents" className="bg-[radial-gradient(ellipse_at_50%_0%,#f5eafd,transparent_53%),linear-gradient(180deg,#fcf9ff,#fff)] px-5 pb-24 pt-44"><div className="mx-auto max-w-6xl"><h1 className="max-w-xl text-5xl font-semibold leading-[0.98] tracking-[-0.07em] md:text-7xl">Bring your own agents<br /><span className="text-[#8a8d93]">or build one that fits</span></h1><p className="mt-6 max-w-lg text-lg leading-7 text-[#7a7d82]">FlowInbox is a tool your agents call, not a wall they hit. Wire it into your own workflows and let them act on your inbox.</p><div className="mt-12"><MailMockup /></div></div></section>
    <section id="mcp" className="bg-[linear-gradient(135deg,#fff0e7,#f9e2ee_50%,#f0e4fb)] px-5 py-24"><div className="mx-auto max-w-6xl"><h2 className="text-5xl font-semibold leading-none tracking-[-0.07em] md:text-7xl">One MCP<br /><span className="text-[#8f8d91]">three ways to use it</span></h2><div className="mt-14 grid gap-10 md:grid-cols-[0.7fr_1.3fr] md:items-center"><div className="space-y-8 text-[#3b3e45]"><div className="flex gap-4"><Bot className="mt-1 h-5 w-5" /><div><h3 className="text-xl font-semibold">Codex</h3><p className="mt-1 max-w-sm text-base text-[#76747b]">Programmatic. Drop the MCP into a CI step or a cron job. Your inbox triage happens before you wake.</p></div></div><div className="flex gap-4"><Sparkles className="mt-1 h-5 w-5" /><div><h3 className="text-xl font-semibold">Claude</h3><p className="mt-1 max-w-sm text-base text-[#76747b]">Conversational. Describe the outcome, skip the steps, and let your assistant run.</p></div></div><div className="flex gap-4 border-l-2 border-[#3b3e45] pl-4"><Hash className="mt-1 h-5 w-5" /><div><h3 className="text-xl font-semibold">Cursor</h3><p className="mt-1 max-w-sm text-base text-[#76747b]">In-flow. The inbox lives beside your code. Review a thread and jump back to your work.</p></div></div></div><div className="rounded-[28px] bg-white/80 p-3 shadow-xl"><div className="rounded-2xl border border-[#e8e1ec] bg-white p-4 font-mono text-[10px] leading-5 text-[#68717b]"><div className="mb-3 rounded-full border border-[#e5e8eb] px-3 py-1">What's in my primary inbox?</div><p>Executed 1 tool</p><p className="mt-2 text-[#2d7ed0]">FlowInbox.search_emails</p><div className="mt-2 overflow-hidden rounded-lg border border-[#edf0f3]"><div className="grid grid-cols-3 border-b bg-[#f7f8fa] p-2"><span>Date</span><span>From</span><span>Subject</span></div>{['Jun 1 · Cursor Team · Improvements to pricing', 'Jun 1 · Lizzie at PostHog · You have the data', 'May 31 · FlowInbox · Your daily inbox brief', 'May 30 · Finance · Receipt matched'].map(row => <div key={row} className="border-b p-2">{row}</div>)}</div></div></div></div></div></section>
    <section id="teams" className="bg-[linear-gradient(180deg,#8bb8f0,#cbe5ff_48%,#8eaee1)] px-5 py-24 text-white"><div className="mx-auto grid max-w-6xl gap-12 md:grid-cols-2 md:items-center"><div><h2 className="max-w-lg text-5xl font-semibold leading-[0.98] tracking-[-0.07em] md:text-7xl">Comment on any email, privately</h2><p className="mt-6 max-w-md text-lg leading-7 text-white/85">Privately chat with your teammates while maintaining the context of the conversation.</p></div><MailMockup comments /></div></section>
    <section className="bg-[linear-gradient(180deg,#719c31,#426f39)] px-5 py-24 text-white"><div className="mx-auto grid max-w-6xl gap-12 md:grid-cols-[0.8fr_1.2fr] md:items-center"><div><h2 className="max-w-lg text-5xl font-semibold leading-[0.98] tracking-[-0.07em] md:text-7xl">Categorize email into channels</h2><p className="mt-6 max-w-md text-lg leading-7 text-white/85">Onboard teammates quickly with shared channels for teams, projects, or any organization.</p></div><div className="rounded-3xl bg-white p-4 text-[#27313b] shadow-2xl"><div className="grid grid-cols-[150px_1fr] gap-4"><div className="space-y-2 text-sm text-[#71808d]"><p className="mb-4 text-xs font-semibold">Channels</p>{['announcements', 'bugs', 'general', 'engineering', 'random', 'updates'].map((name, i) => <div key={name} className={`rounded-lg px-3 py-2 ${i === 2 ? 'bg-[#edf5ec] font-semibold text-[#263e36]' : ''}`}># {name}</div>)}</div><div><h3 className="border-b pb-3 text-sm font-semibold"># general</h3>{['Quick decisions to unblock today', 'Can you take a look?', 'Investor Follow-up', 'Linear x GitHub integration', 'An idea for your team'].map((item, i) => <div key={item} className="border-b py-3 text-xs"><span className="mr-5 font-medium">{['me, Jonathan', 'Janice, Arthur', 'Paul, Charlize', 'Duane', 'Patryk'][i]}</span>{item}</div>)}</div></div></div></div></section>
    <section className="bg-[#fbfbfd] px-5 py-24 text-center"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#7e91a3]">Built for your workflow</p><h2 className="mx-auto mt-5 max-w-3xl text-5xl font-semibold leading-none tracking-[-0.07em] md:text-7xl">Connect once. Let FlowInbox meet your agents wherever they work.</h2><div className="mx-auto mt-14 grid max-w-6xl gap-5 md:grid-cols-3">{[['Quickly connect to Gmail', 'Connect your inbox in seconds, no configuration needed'], ['FlowInbox finds your voice & tone', 'AI learns your style, audiences, patterns, and preferences'], ['Fly through email with confidence', 'See your emails organized with pre-drafted replies']].map(([title, desc], index) => <div key={title} className={`relative min-h-[310px] rounded-[28px] p-7 text-left ${['bg-[#ffe5ec]', 'bg-[#eef8d7]', 'bg-[#ddf8f1]'][index]}`}><span className="absolute -top-4 left-5 flex h-10 w-10 items-center justify-center rounded-full bg-white text-lg text-[#2d7ed0] shadow-sm">{index + 1}</span><h3 className="mt-3 max-w-xs text-3xl font-semibold leading-none tracking-[-0.05em]">{title}</h3><p className="mt-4 max-w-xs text-base text-[#69727c]">{desc}</p><div className="absolute bottom-8 left-1/2 flex h-16 w-16 -translate-x-1/2 items-center justify-center rounded-full bg-white text-[#2d7ed0] shadow-lg">{index === 0 ? <Search /> : index === 1 ? <Sparkles /> : <Check />}</div></div>)}</div></section>
  </main><footer className="bg-white px-6 py-8 text-center text-xs text-[#83909c]">FlowInbox · The inbox your people and agents can work from together.</footer></div>;
}
