import uuid
from datetime import datetime
from typing import Optional, List
from sqlalchemy import String, Text, ForeignKey, Boolean, DateTime, Integer, JSON
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.models.base import Base, GUID


class EmailThread(Base):
    """Email conversation thread model."""
    __tablename__ = "email_threads"

    user_id: Mapped[uuid.UUID] = mapped_column(GUID(), ForeignKey("users.id", ondelete="CASCADE"), index=True, nullable=False)

    gmail_thread_id: Mapped[str] = mapped_column(String(255), index=True, nullable=False)
    subject: Mapped[str] = mapped_column(String(512), default="", nullable=False)
    snippet: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    last_message_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), index=True, nullable=False)
    category: Mapped[str] = mapped_column(String(50), default="primary", nullable=False)  # primary, recruiter, promotions, social, updates
    importance: Mapped[str] = mapped_column(String(50), default="normal", nullable=False)  # low, normal, high, urgent
    needs_reply: Mapped[bool] = mapped_column(Boolean, default=False, index=True, nullable=False)
    has_unanswered_followup: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    channel_id: Mapped[Optional[uuid.UUID]] = mapped_column(GUID(), ForeignKey("channels.id", ondelete="SET NULL"), nullable=True)

    # Real folder & Gmail label flags
    folder: Mapped[str] = mapped_column(String(50), default="inbox", index=True, nullable=False)  # inbox, starred, snoozed, sent, drafts, scheduled, all, spam, trash
    is_starred: Mapped[bool] = mapped_column(Boolean, default=False, index=True, nullable=False)
    is_read: Mapped[bool] = mapped_column(Boolean, default=True, index=True, nullable=False)
    is_archived: Mapped[bool] = mapped_column(Boolean, default=False, index=True, nullable=False)
    is_trashed: Mapped[bool] = mapped_column(Boolean, default=False, index=True, nullable=False)
    is_snoozed: Mapped[bool] = mapped_column(Boolean, default=False, index=True, nullable=False)
    snoozed_until: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)

    # Relationships
    emails: Mapped[List["Email"]] = relationship("Email", back_populates="thread", cascade="all, delete-orphan")



class Email(Base):
    """Individual email message within a thread."""
    __tablename__ = "emails"

    user_id: Mapped[uuid.UUID] = mapped_column(GUID(), ForeignKey("users.id", ondelete="CASCADE"), index=True, nullable=False)
    thread_id: Mapped[uuid.UUID] = mapped_column(GUID(), ForeignKey("email_threads.id", ondelete="CASCADE"), index=True, nullable=False)
    gmail_id: Mapped[str] = mapped_column(String(255), unique=True, index=True, nullable=False)
    sender: Mapped[str] = mapped_column(String(255), index=True, nullable=False)
    sender_email: Mapped[str] = mapped_column(String(255), index=True, nullable=False)
    recipients: Mapped[str] = mapped_column(Text, nullable=False)  # comma-separated emails
    subject: Mapped[str] = mapped_column(String(512), nullable=False)
    body_text: Mapped[str] = mapped_column(Text, nullable=False)
    body_html: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    sent_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), index=True, nullable=False)
    is_incoming: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)

    # Relationships
    thread: Mapped["EmailThread"] = relationship("EmailThread", back_populates="emails")


class Contact(Base):
    """Derived or synced contact info with relationship context."""
    __tablename__ = "contacts"

    user_id: Mapped[uuid.UUID] = mapped_column(GUID(), ForeignKey("users.id", ondelete="CASCADE"), index=True, nullable=False)
    email_address: Mapped[str] = mapped_column(String(255), index=True, nullable=False)
    name: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    role: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)  # recruiter, interviewer, lead, client
    company: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    notes: Mapped[Optional[str]] = mapped_column(Text, nullable=True)


class Draft(Base):
    """Email response draft generated by Writing Agent or user."""
    __tablename__ = "drafts"

    user_id: Mapped[uuid.UUID] = mapped_column(GUID(), ForeignKey("users.id", ondelete="CASCADE"), index=True, nullable=False)
    thread_id: Mapped[Optional[uuid.UUID]] = mapped_column(GUID(), ForeignKey("email_threads.id", ondelete="SET NULL"), nullable=True)
    gmail_draft_id: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    to_email: Mapped[str] = mapped_column(String(255), nullable=False)
    subject: Mapped[str] = mapped_column(String(512), nullable=False)
    body: Mapped[str] = mapped_column(Text, nullable=False)
    is_sent: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)


class Followup(Base):
    """Follow-up candidates identified by Followup Agent."""
    __tablename__ = "followups"

    user_id: Mapped[uuid.UUID] = mapped_column(GUID(), ForeignKey("users.id", ondelete="CASCADE"), index=True, nullable=False)
    thread_id: Mapped[uuid.UUID] = mapped_column(GUID(), ForeignKey("email_threads.id", ondelete="CASCADE"), nullable=False)
    contact_email: Mapped[str] = mapped_column(String(255), nullable=False)
    days_since_contact: Mapped[int] = mapped_column(Integer, nullable=False)
    suggested_draft_id: Mapped[Optional[uuid.UUID]] = mapped_column(GUID(), ForeignKey("drafts.id", ondelete="SET NULL"), nullable=True)
    status: Mapped[str] = mapped_column(String(50), default="pending", nullable=False)  # pending, approved, dismissed


class Task(Base):
    """Productivity action item extracted from email thread."""
    __tablename__ = "tasks"

    user_id: Mapped[uuid.UUID] = mapped_column(GUID(), ForeignKey("users.id", ondelete="CASCADE"), index=True, nullable=False)
    thread_id: Mapped[Optional[uuid.UUID]] = mapped_column(GUID(), ForeignKey("email_threads.id", ondelete="SET NULL"), nullable=True)
    title: Mapped[str] = mapped_column(String(512), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    due_date: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    is_completed: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)


class CalendarEvent(Base):
    """Google Calendar event representation."""
    __tablename__ = "calendar_events"

    user_id: Mapped[uuid.UUID] = mapped_column(GUID(), ForeignKey("users.id", ondelete="CASCADE"), index=True, nullable=False)

    google_event_id: Mapped[str] = mapped_column(String(255), index=True, nullable=False)
    title: Mapped[str] = mapped_column(String(512), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    start_time: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    end_time: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    attendees: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)
