apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: flowinbox
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: flowinbox-backend:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
              name: http
          envFrom:
            - configMapRef:
                name: flowinbox-config
            - secretRef:
                name: flowinbox-secrets
          startupProbe:
            httpGet:
              path: /api/v1/health
              port: 8000
            failureThreshold: 60
            periodSeconds: 2

          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 8000
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 8000
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

